### ISSUE TITLE
Problem with GATLING

### ISSUE THREAD

**Issue by UO276244** [Arquisoft/dede_en3a#133] opened 2022-04-21 17:27 UTC
I'm having a problem while running gatling's recorder. I have created a valid certificate, and i have configured correctly the proxy in Firefox and also added the certificate, but when accessing the web, the products are not rendered in the app.

I can access any part on the web, but when i access any part that make requests to firebase database, nothing is rendered, i guess because it is protected against certain uses of proxy. Any way, i can still use it for testing loads when calculating the shipping, but not for making orders or reviewing existing ones.

Is it enough to make load tests only for calculating the shipping in the backend? I know in a real scenario they wouldn't be enough, but are they for our project?

**Comment by pglez82** [comment] 2022-04-22 07:52
Lets try to fix it first. As you say It can happen that firebase is blocking these petitions. Maybe this information can help?

https://groups.google.com/g/gatling/c/baHROJnjgQk

**Comment by UO276244** [comment] 2022-04-22 09:46
I followed the recomendations of the post of using a HAR file. With 75 users at once, it seems it worked because the orders where correctly added to the DB. 
![image](https://user-images.githubusercontent.com/78870498/164680140-e7ebd6ce-df1a-4c37-bdc0-16eb09a00939.png)

As i'm using a HAR file with all the requests from the browser, there is a lot of "rubish", mainly images and other kind of scripts, so i guess if i delete some of the requests generated, the percentage of success will grow, because most of the failures come from this non-necessary scripts.

Thanks a lot!!

**Comment by pglez82** [comment] 2022-04-28 07:00
Maybe this issue can be closed as the problem is already solved.

**Closed** 2022-04-28 07:09 UTC
Labels: Problem
